@startuml empleados-dc
!include ../estilos/final.iuml
    title "Empleados: diagrama de clases"


    class Departamento {
        nombre: String
        localidad: String [0..1]
    }
    class Empleado {
        nombre: String
        fechaInicio: Date
        fechaFin: Date [0..1]
        salario: Double
        comisión: Double
    }
    'Asociaciones
    Departamento "0..1" -- "0..*" Empleado: trabajaEn >
    Empleado "0..1 Jefe" -- "0..* Subordinado" Empleado: coordina >
    note as RN
        RN-01: Un departamento no puede tener más de cinco empleados;
        la combinación nombre y localidad no se puede repetir.
        RN-02: Un empleado no puede ser su propio jefe;
        la comisión está entre 0 y 1 y su diferencia absoluta no puede
        superar 0.2 (20 puntos porcentuales) en una actualización.
    end note
@enduml
