#!/bin/bash

rm -rf exports/*

./exporta Bodegas/Main.puml
./exporta Espectaculos/Main.puml
./exporta Proyectos/Main.puml
./exporta Usuarios2/Main.puml
./exporta Grados/Main.puml
./exporta Teoria/Main.puml
