#!/bin/bash

rm -rf exports/*

./exporta Aficiones/MainEstatico.puml
./exporta Aficiones/MainDinamico.puml
./exporta Animales/Main.puml
./exporta Apartamentos/Main.puml
./exporta Bodegas/Main.puml
./exporta Empleados/Main.puml
./exporta Espectaculos/Main.puml
./exporta Pedidos/Main.puml
./exporta Proyectos/Main.puml
./exporta Usuarios/Main.puml
./exporta Usuarios2/Main.puml
./exporta Grados/Main.puml
./exporta Teoria/Main.puml